package com.imooc.dao;

import com.imooc.dataobject.GoodsDO;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface GoodsDOMapper {

    List<GoodsDO> listGoods();

    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods
     *
     * @mbggenerated Fri Feb 08 22:58:34 CST 2019
     */
    int insert(GoodsDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods
     *
     * @mbggenerated Fri Feb 08 22:58:34 CST 2019
     */
    int insertSelective(GoodsDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods
     *
     * @mbggenerated Fri Feb 08 22:58:34 CST 2019
     */
    GoodsDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods
     *
     * @mbggenerated Fri Feb 08 22:58:34 CST 2019
     */
    int updateByPrimaryKeySelective(GoodsDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods
     *
     * @mbggenerated Fri Feb 08 22:58:34 CST 2019
     */
    int updateByPrimaryKey(GoodsDO record);

    int increaseSales(@Param("id") Integer id, @Param("amount") Integer amount);
}