package com.imooc.dao;

import com.imooc.dataobject.GoodsStockDO;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface GoodsStockDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_stock
     *
     * @mbggenerated Fri Feb 08 22:58:35 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_stock
     *
     * @mbggenerated Fri Feb 08 22:58:35 CST 2019
     */
    int insert(GoodsStockDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_stock
     *
     * @mbggenerated Fri Feb 08 22:58:35 CST 2019
     */
    int insertSelective(GoodsStockDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_stock
     *
     * @mbggenerated Fri Feb 08 22:58:35 CST 2019
     */
    GoodsStockDO selectByPrimaryKey(Integer id);

    GoodsStockDO selectByGoodsId(Integer goodsId);

    List<GoodsStockDO> selectByGoodsIdList(List<Integer> idList);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_stock
     *
     * @mbggenerated Fri Feb 08 22:58:35 CST 2019
     */
    int updateByPrimaryKeySelective(GoodsStockDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_stock
     *
     * @mbggenerated Fri Feb 08 22:58:35 CST 2019
     */
    int updateByPrimaryKey(GoodsStockDO record);

    int decreaseStock(@Param("goodsId") Integer goodsId, @Param("amount") Integer amount);
}